import type { LucideIcon } from "lucide-react"
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Box,
  Building,
  Calendar,
  CalendarCheck,
  Check,
  CheckCircle,
  Circle,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Droplet,
  Eye,
  EyeOff,
  FileText,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  Gauge,
  Hammer,
  Info,
  List,
  ListChecks,
  Lock,
  MapPin,
  Package,
  Pause,
  Play,
  Plug,
  RefreshCw,
  RotateCw,
  Settings,
  Shield,
  ShieldCheck,
  Square,
  Tag,
  Tags,
  TrendingDown,
  TrendingUp,
  Truck,
  Unlock,
  User,
  Users,
  Wrench,
  X,
  XCircle,
  Zap,
} from "lucide-react"

/** Map of kebab-case icon keys to Lucide icon components. */
const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  box: Box,
  building: Building,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  check: Check,
  "check-circle": CheckCircle,
  circle: Circle,
  clipboard: Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  droplet: Droplet,
  eye: Eye,
  "eye-off": EyeOff,
  "file-text": FileText,
  flag: Flag,
  flame: Flame,
  folder: Folder,
  "folder-open": FolderOpen,
  gauge: Gauge,
  hammer: Hammer,
  info: Info,
  list: List,
  "list-checks": ListChecks,
  lock: Lock,
  "map-pin": MapPin,
  package: Package,
  pause: Pause,
  play: Play,
  plug: Plug,
  "refresh-cw": RefreshCw,
  "rotate-cw": RotateCw,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  square: Square,
  tag: Tag,
  tags: Tags,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  truck: Truck,
  unlock: Unlock,
  user: User,
  users: Users,
  wrench: Wrench,
  x: X,
  "x-circle": XCircle,
  zap: Zap,
}

/**
 * Resolves a Lucide icon component from a kebab-case key.
 * Returns undefined if the icon is not found.
 */
export function getLucideIcon(key: string): LucideIcon | undefined {
  if (!key || typeof key !== "string") return undefined
  return ICON_MAP[key] ?? ICON_MAP[key.toLowerCase()]
}

export interface IconOption {
  key: string
  label: string
}

/**
 * Curated list of CMMS-relevant Lucide icons for statuses, priorities, and maintenance types.
 * Keys are kebab-case matching the ICON_MAP (used for storage).
 */
export const CMMS_ICONS: IconOption[] = [
  { key: "play", label: "Play" },
  { key: "pause", label: "Pause" },
  { key: "square", label: "Square" },
  { key: "circle", label: "Circle" },
  { key: "check", label: "Check" },
  { key: "check-circle", label: "Check circle" },
  { key: "x", label: "X" },
  { key: "x-circle", label: "X circle" },
  { key: "alert-circle", label: "Alert" },
  { key: "alert-triangle", label: "Warning" },
  { key: "info", label: "Info" },
  { key: "clipboard", label: "Clipboard" },
  { key: "clipboard-check", label: "Clipboard check" },
  { key: "clipboard-list", label: "Clipboard list" },
  { key: "wrench", label: "Wrench" },
  { key: "settings", label: "Settings" },
  { key: "calendar", label: "Calendar" },
  { key: "calendar-check", label: "Calendar check" },
  { key: "clock", label: "Clock" },
  { key: "flag", label: "Flag" },
  { key: "folder", label: "Folder" },
  { key: "folder-open", label: "Folder open" },
  { key: "file-text", label: "File" },
  { key: "list", label: "List" },
  { key: "list-checks", label: "List checks" },
  { key: "map-pin", label: "Map pin" },
  { key: "building", label: "Building" },
  { key: "users", label: "Users" },
  { key: "user", label: "User" },
  { key: "truck", label: "Truck" },
  { key: "package", label: "Package" },
  { key: "box", label: "Box" },
  { key: "hammer", label: "Hammer" },
  { key: "plug", label: "Plug" },
  { key: "shield", label: "Shield" },
  { key: "shield-check", label: "Shield check" },
  { key: "lock", label: "Lock" },
  { key: "unlock", label: "Unlock" },
  { key: "eye", label: "Eye" },
  { key: "eye-off", label: "Eye off" },
  { key: "refresh-cw", label: "Refresh" },
  { key: "rotate-cw", label: "Rotate" },
  { key: "trending-up", label: "Trending up" },
  { key: "trending-down", label: "Trending down" },
  { key: "activity", label: "Activity" },
  { key: "zap", label: "Zap" },
  { key: "flame", label: "Flame" },
  { key: "droplet", label: "Droplet" },
  { key: "gauge", label: "Gauge" },
  { key: "tag", label: "Tag" },
  { key: "tags", label: "Tags" },
]
